#! /bin/bash

RESULT_FILE=/tmp/amc-test.log
FAILS=0

ARGS=$@

source ./try_one.sh

for t in t/*/test.sh
do
    try_one $t || FAILS=1
done
for t in t/*/test.pl
do
    try_one "$PERLPATH $t" || FAILS=1
done

exit $FAILS
